Step2 구현
jryoun1/OpenMarket pull request #2
Opened 2021-08-20 15:27 UTC by jryoun1

[구현사항]
1. 화면 구현
- 상품 목록 화면 구현 (tableView와 collectionView를 코드로 생성하고, SegmentControl에 따라서 isHidden을 사용하는 방식으로 구현)
- MVVM 패턴을 적용하여 뷰에 데이터를 띄워줄 수 있도록 구현 <br> (HomeViewController에 ViewModel을 bind해주는 함수와 데이터를 받아 왔을 때 viewModel에 저장해주는 부분있음)
- `ItemListViewModel`과 `ItemListCellViewModel`을 재활용하여 `ItemTableViewCell`과 `ItemCollectionViewCell` 로 가공된 데이터를 넘겨주어 화면에 보여지도록 구현
- `ItemTableViewCell`, `ItemCollectionViewCell`은 xib에 뷰를 그리고 레이아웃을 설정

2. Paging 구현
- `scrollViewDidScroll()` 메서드 내부에서 스크롤이 현재 스크롤뷰의 Offset의 끝에 가게 되면 다음 페이지를 호출할 수 있도록 구현
- `beginPaging()` 함수와 isPaging, hasNextPage, currentPage 프로퍼티들을 통해서 페이징을 구현
- Paging을 할 때 사용자에게 loading 중임을 알리기 위해서 activityIndicator를 `tableViewFooter`, `CollectionViewFooter`에 넣고 Paging할 때만 동작하고 이후에는 멈추도록 구현

[추가구현필요사항]
기존에 step2에서 적용해보기로한 skeleton View의 경우에는 추후에 모든 스텝을 마무리하고 추가해 볼 예정이다.

2021-08-22 05:51 UTC, wonhee009 requested changes

2021-08-22 05:51 UTC, wonhee009 commented on OpenMarket/OpenMarket/ViewModel/View/ItemTableViewCell.swift
> +            if stockString == "품절" {
하드코딩...?

2021-08-22 05:51 UTC, wonhee009 commented on OpenMarket/OpenMarket/ViewModel/View/ItemTableViewCell.swift
> +            stockLabel.text = "오류가 발생했습니다."
하드코딩....??

2021-08-22 05:51 UTC, wonhee009 commented on OpenMarket/OpenMarket/ViewModel/View/ItemTableViewCell.swift
> +        }
복잡해 보이는데 개선... 가능한가여?

2021-08-22 05:51 UTC, wonhee009 commented on OpenMarket/OpenMarket/ViewModel/View/ItemTableViewCell.swift
> +        }
이런거도 분리 부탁드려요....

2021-08-22 05:51 UTC, wonhee009 commented on OpenMarket/OpenMarket/HomeViewController.swift
> +    private var apiRequestLoader: APIRequestLoader<GetItemListAPIRequest>!
이런 프로퍼티들도 ViewModel이 들고있어야하지 않나여?

2021-08-22 05:51 UTC, wonhee009 commented on OpenMarket/OpenMarket/HomeViewController.swift
> +        let titles = ["LIST", "GRID"]
이런 문자열도 따로 관리해주면 좋을거 같아여

2021-08-22 05:51 UTC, wonhee009 commented on OpenMarket/OpenMarket/HomeViewController.swift
> +            return
이런 부분도 case 0이 아니라 LIST, GRID인지 알 수 있게 해주세요

2021-08-22 05:51 UTC, wonhee009 commented on OpenMarket/OpenMarket/HomeViewController.swift
> +        apiRequestLoader.loadAPIReqeust(requestData: page) { [self] itemList, error in
weak는 안해줘도 되는건가여?

2021-08-22 05:51 UTC, wonhee009 commented on OpenMarket/OpenMarket/HomeViewController.swift
> +                self.itemListViewModel.itemList.value?.append(ItemListCellViewModel(item))
ItemListCell에 대한 ViewModel을 따로 정의해놨는데 itemListViewModel의 itemList가 ItemListCellViewModel의 array 타입일 필요가 있나요?
itemList: [Item]으로 정의하고 사용하면 안되나요?

2021-08-22 05:51 UTC, wonhee009 commented on OpenMarket/OpenMarket/Network/APIRequest/GetImageAPIRequest.swift
> +            return UIImage(named: "AirPodMax2")!
기본 이미지의 개념인가여?

2021-08-22 05:51 UTC, wonhee009 commented on OpenMarket/OpenMarket/Utilities/LoadingIndicatorState.swift
> +}
HomeVC에서만 쓸거면 내부 enum으로 정의해도 되지 않을까요?

2021-08-22 05:51 UTC, wonhee009 commented on OpenMarket/OpenMarket/ViewModel/View/ItemTableViewCell.swift
> +        }
"품절" 문자열로 품절 여부 판단보다는 String -> Int가 가능한지로 필터링 하는게 좀 더 안전할거 같은데요

2021-08-24 02:12 UTC, jryoun1 commented on OpenMarket/OpenMarket/Network/APIRequest/GetImageAPIRequest.swift
> +            return UIImage(named: "AirPodMax2")!
@wonhee009 default 처리 나중에 해주는데 수정했습니다!

2021-08-24 02:15 UTC, jryoun1 commented on OpenMarket/OpenMarket/ViewModel/View/ItemTableViewCell.swift
> +        }
@wonhee009 좋은 방법이네여 👍🏻ㅎㅎ
근데 CellViewModel에서 stock이 0 개 이하면 품절로 넘겨주고 
1 개 이상이면 `잔여수량: \(stockWithCommna)` 이렇게 둘 다 String으로 넘겨주는데 확실하게 품절인지 확인하는게 낫지 않을까여??

2021-08-24 03:25 UTC, jryoun1 commented
[수정사항]
1. LoadingIndicatorState enum HomeViewController 내부로 이동
2. SegmentControl enum 생성 
3. 하드 코딩 => 문자열 enum 생성하여 대체 
4. fetchData 함수를 homeviewController에서 ItemListViewModel로 옮김

2021-08-24 09:51 UTC, wonhee009 commented on OpenMarket/OpenMarket/ViewModel/View/ItemTableViewCell.swift
> +        }
이후에 "품절"이 "재고 없음"으로 변경될 경우 같은 예시를 생각해보면 String -> Int가 좀 더 방어적이라고 생각하는데 어떠신가요?

2021-08-24 10:22 UTC, merged